//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.25 at 10:52:20 PM CEST 
//


package cph.asffnldg.classclient.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dk.danielgron.class3.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dk.danielgron.class3.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetClassRequest }
     * 
     */
    public GetClassRequest createGetClassRequest() {
        return new GetClassRequest();
    }

    /**
     * Create an instance of {@link GetAllClassesRequest }
     * 
     */
    public GetAllClassesRequest createGetAllClassesRequest() {
        return new GetAllClassesRequest();
    }

    /**
     * Create an instance of {@link GetAllClassesResponse }
     * 
     */
    public GetAllClassesResponse createGetAllClassesResponse() {
        return new GetAllClassesResponse();
    }

    /**
     * Create an instance of {@link SchoolClass }
     * 
     */
    public SchoolClass createSchoolClass() {
        return new SchoolClass();
    }

    /**
     * Create an instance of {@link GetClassResponse }
     * 
     */
    public GetClassResponse createGetClassResponse() {
        return new GetClassResponse();
    }

    /**
     * Create an instance of {@link Teacher }
     * 
     */
    public Teacher createTeacher() {
        return new Teacher();
    }

}
